FAW8x4:
  model: "FAW J6 8x4"
  cuzov: "models/FAW-Cuzov.bam"
  napolnitel: "models/FAW-Napolnitel.bam"
  other: "models/FAW-Other.bam"
  max_volume: 33
  ground_plane: 2.0

FAW6x4:
  model: "FAW J6 6x4"
  cuzov: "models/FAW3x3-Cuzov.bam"
  napolnitel: "models/FAW3x3-Napolnitel.bam"
  other: "models/FAW3x3-Other.bam"
  max_volume: 21
  ground_plane: 2.0

Scania:
  model: "Scania"
  cuzov: "models/Scania-Cuzov.bam"
  napolnitel: "models/Scania-Napolnitel.bam"
  other: "models/Scania-Other.bam"
  max_volume: 20
  ground_plane: 2.6

Kerax:
  model: "Kerax"
  cuzov: "models/Kerax-Cuzov.bam"
  napolnitel: "models/Kerax-Napolnitel.bam"
  other: "models/Kerax-Other.bam"
  max_volume: 25
  ground_plane: 2.0

Kamaz:
  model: "Kamaz"
  cuzov: "models/Kamaz-Cuzov.bam"
  napolnitel: "models/Kamaz-Napolnitel.bam"
  other: "models/Kamaz-Other.bam"
  max_volume: 10
  ground_plane: 2.25

HooperType1:
  model: "HooperType1"
  cuzov: "models/Hooper1-Cuzov.bam"
  napolnitel: "models/Hooper1-Napolnitel.bam"
  other: "models/Hooper1-Other.bam"
  max_volume: 48
  ground_plane: 2.5

HooperType2:
  model: "HooperType2"
  cuzov: "models/Hooper2-Cuzov.bam"
  napolnitel: "models/Hooper2-Napolnitel.bam"
  other: "models/Hooper2-Other.bam"
  max_volume: 88
  ground_plane: 2.8

Shackman-X3000-6x4-standard:
  model: "Shackman-X3000-6x4-standard"
  cuzov: "models/Shackman-X3000-6x4-standard-Cuzov.bam"
  napolnitel: "models/Shackman-X3000-6x4-standard-Napolnitel.bam"
  other: "models/Shackman-X3000-6x4-standard-Other.bam"
  max_volume: 19.32
  ground_plane: 2.6

Shackman-X3000-8x4-standard:
  model: "Shackman-X3000-8x4-standard"
  cuzov: "models/Shackman-X3000-8x4-standard-Cuzov.bam"
  napolnitel: "models/Shackman-X3000-8x4-standard-Napolnitel.bam"
  other: "models/Shackman-X3000-8x4-standard-Other.bam"
  max_volume: 26
  ground_plane: 2.6

Shackman-X3000-6x4-tall:
  model: "Shackman-X3000-6x4-tall"
  cuzov: "models/Shackman-X3000-6x4-tall-Cuzov.bam"
  napolnitel: "models/Shackman-X3000-6x4-tall-Napolnitel.bam"
  other: "models/Shackman-X3000-6x4-tall-Other.bam"
  max_volume: 25
  ground_plane: 2.6

Shackman-X3000-8x4-tall:
  model: "Shackman-X3000-8x4-tall"
  cuzov: "models/Shackman-X3000-8x4-tall-Cuzov.bam"
  napolnitel: "models/Shackman-X3000-8x4-tall-Napolnitel.bam"
  other: "models/Shackman-X3000-8x4-tall-Other.bam"
  max_volume: 34
  ground_plane: 2.6

FAW-J6-6x4-standard:
  model: "FAW-J6-6x4-standard"
  cuzov: "models/FAW-J6-6x4-standard-Cuzov.bam"
  napolnitel: "models/FAW-J6-6x4-standard-Napolnitel.bam"
  other: "models/FAW-J6-6x4-standard-Other.bam"
  max_volume: 20
  ground_plane: 2.6

FAW-J6-8x4-standard:
  model: "FAW-J6-8x4-standard"
  cuzov: "models/FAW-J6-8x4-standard-Cuzov.bam"
  napolnitel: "models/FAW-J6-8x4-standard-Napolnitel.bam"
  other: "models/FAW-J6-8x4-standard-Other.bam"
  max_volume: 26
  ground_plane: 2.6

FAW-J6-6x4-tall:
  model: "FAW-J6-6x4-tall"
  cuzov: "models/FAW-J6-6x4-tall-Cuzov.bam"
  napolnitel: "models/FAW-J6-6x4-tall-Napolnitel.bam"
  other: "models/FAW-J6-6x4-tall-Other.bam"
  max_volume: 25
  ground_plane: 2.6

FAW-J6-8x4-tall:
  model: "FAW-J6-8x4-tall"
  cuzov: "models/FAW-J6-8x4-tall-Cuzov.bam"
  napolnitel: "models/FAW-J6-8x4-tall-Napolnitel.bam"
  other: "models/FAW-J6-8x4-tall-Other.bam"
  max_volume: 34
  ground_plane: 2.6