[Interface]
PrivateKey = KAEKMyX87XxX+nzsxCpiEXr8YtdptHBpXl7OBSQLLUw=
ListenPort = 51820
Address = 10.123.0.6/32
DNS = 192.168.123.1

[Peer]
PublicKey = iIJY31cIE8ZOYTZHZ8CEtMpxQqpWqIgtqjdQsIV6Ow0=
AllowedIPs = 192.168.123.0/24
Endpoint = 78.25.191.12:13231
PersistentKeepalive = 25